services:
  poc:
    build: .
    image: poc:latest
    command: ["odoo", "-c", "prod-env.conf", "-i", "factory"]
    restart: always
    ports:
      - "80:8069"
    volumes:
      - odoo-poc-fs:/var/lib/odoo

volumes:
  odoo-poc-fs:
