services:
  ev-odoo:
    build: .
    image: poc:latest
    command: ["-c", "env.conf", "-i", "factory"]
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - odoo-poc-fs:/var/lib/odoo

volumes:
  odoo-poc-fs:
