services:
  poc:
    build: .
    image: poc:latest
    command: ["-i", "factory"]
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - odoo-poc-fs:/var/lib/odoo

volumes:
  odoo-poc-fs:
