[options]
; Administration configurations
log_level = info
; logfile = /dev/stdout
addons_path = ./custom-addons
store_attachment = True

; Database configurations
db_host = odoo-poc-db.cepyqk2scj6h.us-east-1.rds.amazonaws.com
db_port = 5432
db_user = odoo
db_password = DpzMdbqawLtcnp0O6G4y
db_name = odoo-18

; Multi-database configurations
list_db = True
; dbfilter = ^%s$

; HTTP server configurations
http_port = 80
gevent_port = 8072
proxy_mode = False

; Security configurations
limit_memory_soft = 6400000000
limit_memory_hard = 7680000000
limit_time_cpu = 60
limit_time_real = 120

; Email configurations
; smtp_server = smtp.gmail.com
; smtp_port = 587
; smtp_user = your_email@example.com
; smtp_password = your_email_password
; smtp_encryption = starttls


