services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - odoo-18-network
    ports:
      - "5432:5432"

volumes:
  postgres-data:
